version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
     - ./src/:/var/www/html/
     - ./config/:/var/www/config/
     - ./private/:/var/www/private/

  db:
    image: "mariadb:latest"
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
    env_file: config/env.list
  pma:
    image: "phpmyadmin/phpmyadmin:latest"
    ports:
      - "8081:80"